"""phase0 schema

Revision ID: 4b4e9a2d0b92
Revises: 
Create Date: 2026-05-11 16:51:57.192556+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b4e9a2d0b92'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkthroughs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('suggested_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hunk_captions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_diff', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('walkthrough_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('old_start', sa.Integer(), nullable=False),
    sa.Column('old_count', sa.Integer(), nullable=False),
    sa.Column('new_start', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=False),
    sa.Column('context_after', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthroughs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walkthrough_id', 'ref', name='uq_hunks_walkthrough_ref')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('walkthrough_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthroughs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walkthrough_id', 'ref', name='uq_threads_walkthrough_ref')
    )
    op.create_table('thread_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('narration_edited_at', sa.DateTime(), nullable=True),
    sa.Column('narration_edited_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'step_order', name='uq_thread_steps_thread_order')
    )
    op.create_table('thread_step_hunks',
    sa.Column('thread_step_id', sa.UUID(), nullable=False),
    sa.Column('hunk_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hunk_id'], ['hunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_step_id'], ['thread_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_step_id', 'hunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_step_hunks')
    op.drop_table('thread_steps')
    op.drop_table('threads')
    op.drop_table('hunks')
    op.drop_table('walkthroughs')
    # ### end Alembic commands ###
