"""field_edits history

Revision ID: 6fd55d764c78
Revises: 4b4e9a2d0b92
Create Date: 2026-05-11 18:03:16.534253+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd55d764c78'
down_revision: Union[str, Sequence[str], None] = '4b4e9a2d0b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('walkthrough_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('editor', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthroughs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_edits_target', 'field_edits', ['target_kind', 'target_id', 'field', 'created_at'], unique=False)
    op.create_index('ix_field_edits_walkthrough', 'field_edits', ['walkthrough_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_edits_walkthrough', table_name='field_edits')
    op.drop_index('ix_field_edits_target', table_name='field_edits')
    op.drop_table('field_edits')
    # ### end Alembic commands ###
